### PR TITLE
[fix] Changed carrier to use the `--kubeconfig`/`-c` cli options.

### LINKED ISSUE #89: cli ignores option --kubeconfig/-c
Testing PR #43 for #40 I noticed that `carrier` ignores the `--kubeconfig` option to provide the path to the kubeconfig to use.
I approved the PR even so, because I further determined that this issue was present on main as well, and thus did not came from #43.

`carrier` looks to solely use the environment variable `KUBECONFIG` to determine where to find the cluster.

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fixes #89.

:fireworks: It was a nice surprise that just the removal of the replicated setup of `--kubeconfig` in all the individual commands, and replacing it with a single centralized root level setup was enough to also fix the issue. Seems that the config code expected such a root level flag, and simply ignored it as `not set` when it was not present.

### CODE REVIEW

File: cli/cmd/internal/client/install.go [hunk 1]
```diff
@@ -33,15 +32,8 @@ var CmdInstall = &cobra.Command{
...
-	pf := CmdInstall.PersistentFlags()
-
-	argToEnv := map[string]string{}
-
-	cmd.KubeConfigFlags(pf, argToEnv)
-	cmd.AddEnvToUsage(CmdInstall, argToEnv)
-
-	CmdInstall.Flags().BoolP("verbose", "v", true, "Wether to print logs to stdout")
-	CmdInstall.Flags().BoolP("interactive", "i", false, "Whether to ask the user or not")
+	CmdInstall.Flags().BoolP("verbose", "v", true, "Whether to print logs (stdout) or not")
```
Comment (jimmykarily) [inline cli/cmd/internal/client/install.go:35]: Since you are at it, the description should say something like:

```
Print more detailed messages
```

because we do print logs to stdout anyway.

**Review by jimmykarily — APPROVED** [review]

File: cli/cmd/internal/client/install.go (hunk 1 above)
Comment (andreas-kupries) [reply cli/cmd/internal/client/install.go:35]: Ok. Will do. Just a moment.

Comment (andreas-kupries) [reply cli/cmd/internal/client/install.go]: Done with commit 72726e959cd047b11a6b487091306ad48b80d7a5
