### PR TITLE
Fix Un/bind service in conflict

### LINKED ISSUE #221: CI fails with 4 Gingko runners
See https://github.com/SUSE/carrier/actions/runs/654956612.
Fails during `doesn't delete a bound service [It]`

Previous runs (with 2 Ginkgo runners) were successful.

@andreas-kupries :point_up_2: :wink:

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fixes #221 

It is expected that the loop will resolve quickly. The most likely reason for it is that the service is bound/unbound concurrently. In that case the loop breaks at the recheck for service un/bound.

### CODE REVIEW

File: internal/application/application.go [hunk 1]
```diff
@@ -131,44 +139,53 @@ func (a *Application) Bind(service interfaces.Service) error {
...
+		deployment.Spec.Template.Spec.Volumes = volumes
+		deployment.Spec.Template.Spec.Containers[0].VolumeMounts = volumeMounts
+
+		_, err = a.kubeClient.Kubectl.AppsV1().Deployments(deployments.WorkloadsDeploymentID).Update(
+			context.Background(),
+			deployment,
+			metav1.UpdateOptions{},
+		)
+
+		if err == nil || !apierrors.IsConflict(err) {
```
Comment (kkaempf) [inline internal/application/application.go:181]: This is essentially the same exit criteria as in lines 113 - 118 above. I would use the same code (two separate `if`` statements) at both places

**Review by kkaempf — CHANGES_REQUESTED** [review]
Ok except for the one comment

File: internal/application/application.go (hunk 1 above)
Comment (andreas-kupries) [reply internal/application/application.go:181]: Ok. A moment ...

Comment (andreas-kupries) [reply internal/application/application.go]: Addressed with commit 7ae5bb8452eda05992bb49eb97d524efdb6b8fd1

**Review by kkaempf — APPROVED** [review]
lgtm
